### ISSUE TITLE
Can't get this to work on Sonoma

### ISSUE THREAD

**Issue by wotaen** [borekb/macos-keyboards#7]
Followed up the readme, and keyboard doesn't appear in the Input sources
<img width="594" alt="Screenshot 2023-10-19 at 14 39 10" src="https://github.com/borekb/macos-keyboards/assets/715052/b0e295da-fc3b-4f7d-99c6-156d7c0a59a6">

**Comment by borekb** [comment]
I haven't tried a clean setup on Sonoma but after upgrading from Ventura, everything works fine:

<img width="827" alt="Screenshot 2023-10-19 at 15 26 02" src="https://github.com/borekb/macos-keyboards/assets/101152/88c879dc-8492-45ff-a25a-276ee3131e3c">

I think I vaguely remember a similar issue in the past, maybe the settings dialog caches incorrect list of keyboards, can you try restarting?

**Comment by wotaen** [comment]
> I haven't tried a clean setup on Sonoma but after upgrading from Ventura, everything works fine:
> <img alt="Screenshot 2023-10-19 at 15 26 02" width="827" src="https://user-images.githubusercontent.com/101152/276630070-88c879dc-8492-45ff-a25a-276ee3131e3c.png">
> 
> I think I vaguely remember a similar issue in the past, maybe the settings dialog caches incorrect list of keyboards, can you try restarting?

Indeed, after restart it works fine. Thank you!

**Comment by borekb** [comment]
Good!
